apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf6
  annotations:
    contivpp.io/custom-if: tap1/tap/stub
  labels:
    cnf: linux-cnf6
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
