---
# Create three linux CNFs - the second CNFs with 2 tap intefaces - for multi-node SFC
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf17
  annotations:
    contivpp.io/custom-if: tap1/tap/stub
  labels:
    cnf: linux-cnf17
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
  nodeName: k8s-master
---
# Linux CNF 3 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf18
  annotations:
    contivpp.io/custom-if: tap1/tap/stub
  labels:
    cnf: linux-cnf18
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
  nodeName: k8s-master
