apiVersion: v1
kind: Pod
metadata:
  name: iperf-overlay-server
  labels:
    app: iperf-overlay-server
spec:
  containers:
  - name: iperf-overlay-server
    image: jmarhee/iperf:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-overlay-client
  labels:
    app: iperf-overlay-client
spec:
  containers:
  - name: iperf-overlay-client
    image: jmarhee/iperf:latest

