---
apiVersion: contivpp.io/v1
kind: ServiceFunctionChain
metadata:
  name: simple-chain
spec:
  chain:
    - name: CNF 1
      type: Pod
      podSelector:
        cnf: cnf1
      outputInterface: memif1

    - name: CNF 2
      type: Pod
      podSelector:
        cnf: cnf2
      inputInterface: memif1
