apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # ldpreload-related labels
        ldpreload: "true"
        scopeglobal: "true"
    spec:
      # optional - deploy on preferred node
#      nodeSelector:
#        kubernetes.io/hostname: ubuntu
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          image: nginx
          ports:
            - containerPort: 80
          securityContext:
            privileged: true