---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ft2-rep-linux-cnf1
  labels:
   cnf: ft2-linux-cnf1-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: ft2-linux-cnf1-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub
      labels:
        cnf: ft2-linux-cnf1-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"
---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ft2-rep-linux-cnf2
  labels:
   cnf: ft2-linux-cnf2-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: ft2-linux-cnf2-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
      labels:
        cnf: ft2-linux-cnf2-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"

---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ft2-rep-linux-cnf3
  labels:
   cnf: ft2-linux-cnf3-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: ft2-linux-cnf3-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
      labels:
        cnf: ft2-linux-cnf3-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"
---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ft2-rep-linux-cnf4
  labels:
   cnf: ft2-linux-cnf4-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: ft2-linux-cnf4-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
      labels:
        cnf: ft2-linux-cnf4-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"

---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ft2-rep-linux-cnf5
  labels:
   cnf: ft2-linux-cnf5-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: ft2-linux-cnf5-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
      labels:
        cnf: ft2-linux-cnf5-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"
---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ft2-rep-linux-cnf6
  labels:
   cnf: ft2-linux-cnf6-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: ft2-linux-cnf6-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
      labels:
        cnf: ft2-linux-cnf6-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"
---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ft2-rep-linux-cnf7
  labels:
   cnf: ft2-linux-cnf7-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: ft2-linux-cnf7-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub
      labels:
        cnf: ft2-linux-cnf7-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"
