---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf100
  annotations:
    contivpp.io/custom-if: tap1/tap/stub
  labels:
    cnf: linux-cnf100
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
  nodeName: k8s-master
---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf101
  annotations:
    contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
  labels:
    cnf: linux-cnf101
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
---
# Linux CNF 2 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf102
  annotations:
    contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
  labels:
    cnf: linux-cnf102
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"

---
# Linux CNF 2 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf103
  annotations:
    contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
  labels:
    cnf: linux-cnf103
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
  nodeName: k8s-master
---
# Linux CNF 2 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: v1
kind: Pod
metadata:
  name: linux-cnf104
  annotations:
    contivpp.io/custom-if: tap1/tap/stub
  labels:
    cnf: linux-cnf104
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command:
        - sleep
        - "3600"
  nodeName: k8s-master
