---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep-linux-cnf1
  labels:
   cnf: linux-cnf1-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: linux-cnf1-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub
      labels:
        cnf: linux-cnf1-rp
    spec:
      containers:
        - name: iperf-overlay-client
          image: jmarhee/iperf:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true

---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep-linux-cnf2
  labels:
   cnf: linux-cnf2-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: linux-cnf2-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
      labels:
        cnf: linux-cnf2-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"

---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep-linux-cnf3
  labels:
   cnf: linux-cnf3-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: linux-cnf3-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub, tap2/tap/stub
      labels:
        cnf: linux-cnf3-rp
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sleep
            - "3600"

---
# Linux CNF 1 pod definition. Pod is connected with one additional tap interface
# in the "stub" network = meaning that it won't have any IP address assigned.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep-linux-cnf4
  labels:
   cnf: linux-cnf4-rp
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      cnf: linux-cnf4-rp
  template:
    metadata:
      annotations:
        contivpp.io/custom-if: tap1/tap/stub
      labels:
        cnf: linux-cnf4-rp
    spec:
      containers:
        - name: iperf-overlay-server
          image: jmarhee/iperf:latest
          ports:
          - containerPort: 5001
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
