---
apiVersion: contivpp.io/v1
kind: ServiceFunctionChain
metadata:
  name: linux-chain-replicaset10
spec:
  chain:
    - name: CNF 1
      type: Pod
      podSelector:
        cnf: linux-cnf1-rp
      interface: tap1

    - name: CNF 2
      type: Pod
      podSelector:
        cnf: linux-cnf2-rp
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 3
      type: Pod
      podSelector:
        cnf: linux-cnf3-rp
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 4
      type: Pod
      podSelector:
        cnf: linux-cnf4-rp
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 5
      type: Pod
      podSelector:
        cnf: linux-cnf5-rp
      interface: tap1
